name: share_youtubefile
on:
  workflow_dispatch:
    inputs:
      file_URL:
        description: 'input file URL'
        required: true
        default: 'https://www.youtube.com/watch?v=xxxxxxxxxxx'
      video_fomat:
        description: 'input video fomat:160/mp4/256X144.133/mp4/426x244,18/mp4/540x360,22/mp4/1280x720,43/webm/640x360'
        required: true
        default: '22'        

# env:
#   FILE_ID: 1HbaB7glgDTYWrE4ieBkX6uK0sT223hCl

jobs:
  downgdrive:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: downfromgdrive
        run: |
          sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
          sudo chmod a+rx /usr/local/bin/youtube-dl
          sudo mkdir -p ./youtubesharefiledir
          sudo chown $USER:$GROUPS ./youtubesharefiledir 
          /usr/local/bin/youtube-dl  --list-formats '${{ github.event.inputs.file_URL }}'
          /usr/local/bin/youtube-dl  -f ${{ github.event.inputs.video_fomat }} '${{ github.event.inputs.file_URL }}' -o './youtubesharefiledir/%(title)s_%(id)s.%(ext)s'
      -
        name: Upload file to WeTransfer
        run: |
          tar -czvf youtubesharefiledir.tar.gz ./youtubesharefiledir
          curl -fsSL git.io/file-transfer | sh
          ./transfer wet -s -p 16 --no-progress youtubesharefiledir.tar.gz 2>&1 | tee wetransfer.log
          echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
          echo "::set-output name=url::$(cat wetransfer.log | grep https | cut -f3 -d" ")"