name: share_youtubefile
on:
  workflow_dispatch:
    inputs:
      file_ID:
        description: 'input file ID'
        required: true
        default: 'abc123456789012345678901234567890'
      file_name:
        description: 'input file name'
        required: true
        default: 'test.gz'        

# env:
#   FILE_ID: 1HbaB7glgDTYWrE4ieBkX6uK0sT223hCl

jobs:
  downgdrive:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: downfromgdrive
        run: |
          sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
          sudo chmod a+rx ./bin/youtube-dl
          sudo mkdir -p ./youtubesharefiledir
          sudo chown $USER:$GROUPS ./youtubesharefiledir 
          ./bin/youtube-dl 
          ./bin/youtube-dl youtube-dl -f worst https://www.youtube.com/watch?v=6wtvyzKj2n8 -o ./youtubesharefiledir
          # cd  /sharefiledir 
          # wget -c --limit-rate=20m -P ./sharefiledir  https://drive.google.com/uc?id=${{ github.event.inputs.file_ID }}&export=download  
          # wget  --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=${{ github.event.inputs.file_ID }}' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=${{ github.event.inputs.file_ID }}" -O ${{ github.event.inputs.file_name }}
          # mv  ${{ github.event.inputs.file_name }} ./sharefiledir
          

      -
        name: Upload file to WeTransfer
        run: |
          tar -czvf youtubesharefiledir.tar.gz ./youtubesharefiledir
          curl -fsSL git.io/file-transfer | sh
          ./transfer wet -s -p 16 --no-progress youtubesharefiledir.tar.gz 2>&1 | tee wetransfer.log
          echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
          echo "::set-output name=url::$(cat wetransfer.log | grep https | cut -f3 -d" ")"